### ISSUE TITLE
Changing timeouts is too difficult

### ISSUE THREAD

**Issue by i-am-the-slime** [purescript-spec/purescript-spec#100]
What should be a pretty straightforward use case becomes pretty crazy (and ugly)

```
main ∷ Effect Unit
main = do
  specs <- discover "\\.*Spec"
  runSpecT config [ consoleReporter ] specs # un Identity # launchAff_
  where
  config =
    defaultConfig
      { slow = 5.0 # Seconds # fromDuration
      , timeout = Nothing
      }
```

How about `runSpecWithConfig` in a way that the `un Identity` can be avoided?

**Comment by safareli** [comment]
https://github.com/purescript-spec/purescript-spec/releases/tag/v4.0.1
