### ISSUE TITLE
itOnly still evalutates?

### ISSUE THREAD

**Issue by mushishi78** [purescript-spec/purescript-spec#110]
I've only just started using purescript-spec and didn't look into it deeply, but when I tried to use `Debug.Trace` to try to work out why my test wasn't passing and then put `itOnly` on the test I was interested in, the trace seemed to log all the tests even though the test output implied only the one test had run. Does this mean that all the other tests are still evaluated? That doesn't seem ideal to me.

**Comment by i-am-the-slime** [comment]
How did you use `Debug.Trace`? If you put it at the beginning of a `do` block it might get evaluated when you don't mean it to.

**Comment by mushishi78** [comment]
It was a while ago now so I can't remember, but if that's a likely explanation then I don't mind this issue being closed and I'll open an new issue next time I give it a go and it still doesn't work

**Comment by i-am-the-slime** [comment]
Okay, please reopen if you run into it again!
