### ISSUE TITLE
Warning when specifying the type of a Spec

### ISSUE THREAD

**Issue by tonicebrian** [purescript-spec/purescript-spec#147]
I'm defining several specs in different modules and purty complains about unspecified type. I've added the `spec :: Spec Unit` to the topmost spec, but then I'm getting this compiler warning:

```
  21  spec :: Spec Unit
      ^^^^^^^^^^^^^^^^^

  A custom warning occurred while solving type class constraints:
    Data.Map's `Semigroup` instance is now unbiased and differs from the left-biased instance defined in PureScript releases <= 0.13.x.
  in value declaration spec
```

what would be the right way to specify the type of a spec that I'll want to combine later in `Main.purs` ?

**Comment by fsoikin** [comment]
This is the right way. You're just using newer package set than Spec was last modified against.

**Comment by tonicebrian** [comment]
So, is it a matter of you releasing a new version to regisitry? I don't get what would be the solution to this.

**Comment by fsoikin** [comment]
Yes, exactly, it's a matter of releasing a new version.

**Comment by tonicebrian** [comment]
Looking forward to it then. Thanks!!

**Comment by fsoikin** [comment]
Actually, on closer inspection, it appears there is something fishy with your code. The `Spec` type doesn't touch `Map` in any way, and the only place `Map` is used in this library at all is in the reporters, which don't come into play at the stage of defining test cases.

Where do you import that `Spec` type from?

**Comment by tonicebrian** [comment]
I think I was able to track down the problem but still no clue on why it warns on the Spec. First I import spec using:

```
import Test.Spec (describe, it, Spec)
import Test.Spec.Assertions (fail, shouldEqual)
```

Then I have a test that is record with a field that is a Map of Maps. Having it here as reference:

```
          , techTrack:
              M.fromFoldable
                [ Tuple GermanEmpire (M.fromFoldable [ Tuple Box1 [ Just Offensive ] ])
                , Tuple FrancoBritishEmpire (M.fromFoldable [ Tuple Box2 [ Nothing ] ])
                , Tuple AustroHungarianEmpire mempty
                , Tuple RussianEmpire mempty
                ]
```
The last 2 lines are the culprits. When I use mempty as in haskell I get the `Spec Unit` warning. If I change it to `M.empty` the problem goes away. 

If it is of any help, the assertions are sequenced because I didn't want a single test for big nested data structure:

```
      case parseJson golden >>= decodeJson of
        Left e -> fail ("Couldn't deserialize the golden file: " <> printJsonDecodeError e)
        Right (UpdateGameState obtained) -> do
          obtained.victoryPoints `shouldEqual` expected.victoryPoints
          obtained.techTrack `shouldEqual` expected.techTrack
          obtained.missionsTrack `shouldEqual` expected.missionsTrack
          obtained.turn `shouldEqual` expected.turn
          obtained.counters `shouldEqual` expected.counters
          obtained.areaControl `shouldEqual` expected.areaControl
        Right _ -> fail ("The BEMsg in the file is not an UpdateGameState")
```

Does it sound a ring on you?

**Comment by fsoikin** [comment]
Well yes, that sounds exactly right: you're using `mempty` for a `Map`, so you're using the `Monoid Map` instance, and that's what gives you a warning.
