### ISSUE TITLE
Add the ability to set up variables on the describe block

### ISSUE THREAD

**Issue by Risto-Stevcev** [purescript-spec/purescript-spec#44]
If you have some state you want to test in multiple `it` blocks, instead of having to instantiate it multiple times, it would be nice to be able to do it once in the `describe` block for those specs. Ie:

```purescript
describe "some state" do
  someRef <- readSTRef myRef
  someArray <- freeze mySTArray

  it "should have this property" do
    ...

  it "should have that property" do
    ...
```

**Comment by owickstrom** [comment]
Could this be a variant of #43, if we separate `beforeEach`/`before`, and `afterEach`/`after`?

**Comment by Risto-Stevcev** [comment]
I guess it depends on how it's implemented. If `before` and `after` look similar to `it`, then the variables wouldn't be in scope to use it in this way

**Comment by owickstrom** [comment]
Yes. I'd like for `before` and `after` to make it blocks be functions instead. For every `before`/`each` you nest, the `it` blocks get a new argument:

```
describe "some state" $ before readRef $ before readArray $ do

  it "should have this property" $ \ref array -> do
    ...

  it "should have that property" $ \ref array -> do
    ...
```

Not sure the current design makes that very simple to implement, but I think it would be very nice to have. :)

**Comment by felixSchl** [comment]
To me, hspec's hooks API looks like a good idea to mirror to achieve this: https://hackage.haskell.org/package/hspec-2.4.3/docs/Test-Hspec.html#t:ActionWith.

I don't think it would be terribly hard to make this happen. I wish I had the time to tinker with this, looks like a fun task

**Comment by owickstrom** [comment]
@felixSchl Thanks, will have a look at it.

I hope I can find some time, too. It does not look very bright in the coming week. :/

**Comment by owickstrom** [comment]
Still, I have no time to work on this. Anyone who wants to give it a shot?
