### ISSUE TITLE
Custom compile warning for `itOnly` and `describeOnly`

### ISSUE THREAD

**Issue by felixSchl** [purescript-spec/purescript-spec#63]
What do you think of the idea to have `itOnly` and `describeOnly` cause compile warnings similar to how `traceAnyA` and friends does. I can't speak for others, but I have accidentally committed an `itOnly` block far too many times, not realizing.

**Comment by safareli** [comment]
I think it's a good idea! if this is welcoming change for others too I can open a PR.

**Comment by owickstrom** [comment]
This is included in #83 , correct?

**Comment by safareli** [comment]
yes
