### ISSUE TITLE
`lit` - create a spec whose body is its description

### ISSUE THREAD

**Issue by lisp-ceo** [purescript-spec/purescript-spec#85]
Good evening, greetings from Australia and thank you for your amazing work on purescript!

Occasionally I'll have a `Spec` so short and to-the-point that a textual description of it serves only to duplicate the literal interpretation of the expression.

```purescript
it "accepts strings that contains substrings" $
  "foobar" `AS.shouldContain` "foo"
```
(From `Test.Spec.AssertionSpec`)

Ruby uses polymorphism to accept a spec that only provides a block.

```ruby
  it { expect("foobar").to contain "foo" }
```
(From http://www.betterspecs.org/#short)

`lit` creates a spec for test cases where the code reads as a literal description of its behaviour. 

This requires a degree of connoisseurship as the spec reporter emits empty lines as spec descriptions:

```
* Build successful.
* Running tests...
 Test
  Spec
   Runner
    ✓︎ collects "it" and "pending" in Describe groups
    ✓︎ collects "it" and "pending" with shared Describes
    ✓︎ filters using "only" modifier on "describe" block
    ✓︎ filters using "only" modifier on nested "describe" block
    ✓︎ filters using "only" modifier on "it" block
    ✓︎ supports async
 Test
  Spec
   Assertions
    String
     shouldContain
      ✓︎ accepts strings that contains substrings
      ✓︎ 
      ✓︎ rejects strings that does not contain substrings
```

However, I would argue that for smaller projects, the cardinality of the specs is sufficient to determine success: 

```
* Build successful.
* Running tests...
 Test
  Spec
   Runner
    ✓︎ 
    ✓︎ 
    ✓︎ 
    ✓︎ 
    ✓︎ 
    ✓︎ 
 Test
  Spec
   Assertions
    String
     shouldContain
      ✓︎ 
      ✓︎ 
      ✓︎ 
```

And in the case of failure, the ordinality of the failure is sufficient to locate it:
```
* Building project in /Users/htmldrum/code/purescript/purescript-spec
Compiling Test.Spec.AssertionSpec
Compiling Test.Main
* Build successful.
* Running tests...
 Test
  Spec
   Runner
    ✓︎ collects "it" and "pending" in Describe groups
    ✓︎ collects "it" and "pending" with shared Describes
    ✓︎ filters using "only" modifier on "describe" block
    ✓︎ filters using "only" modifier on nested "describe" block
    ✓︎ filters using "only" modifier on "it" block
    ✓︎ supports async
 Test
  Spec
   Assertions
    String
     shouldContain
      ✓︎ accepts strings that contains substrings
      1) 
      ✓︎ rejects strings that does not contain substrings
...
57 passing
3 pending
1 failed

1) Test Spec Assertions String shouldContain 
  "foo" ∉ "fozbar"
* ERROR: Subcommand terminated with exit code 1
```

Thank you for your time.

**Comment by felixmulder** [comment]
Hey! Thanks for the kind words 🙂

How would you figure out which test failed with this approach?

**Comment by owickstrom** [comment]
Thanks for the informative suggestion!

I can see the appeal of not having to write a description for "self-descriptive" tests. But without some way of showing the assertion source code when tests fail (which I think wouldn't be practical in PureScript) I'm failing to see how this is valuable.

Additionally, unless purescript-spec would do something special with _lit_ tests other than use a blank description, this is easy to add as an alias in your own test suite. You could have a utils module or something with:

```purescript
lit = it ""
```

I'm happy to be convinced otherwise, though. :slightly_smiling_face:

**Comment by CDaubert77** [comment]
I'm not sure

**Comment by safareli** [comment]
If you don't care about naming tests then instead of:
```purs
describe "Data" do
  describe "Foo" do
    it "" testA
    it "" testB
```

You can do this too:
```purs
describe "Data" do
  it "Foo" do
    testA
    testB
```


I agree with @owickstrom points, so close this for now.
