### ISSUE TITLE
sequential isn't working

### ISSUE THREAD

**Issue by ford-prefect** [purescript-spec/purescript-spec#88]
While writing some tests that need to run sequentially, I tried using `sequential` from 4.0.0-rc1, but it does not seem to actually run the tests in sequence. The code is at:

  https://github.com/ford-prefect/purescript-redis/commit/2c04b231ac9487dd86b8456d34767f661e4e64f9

**Comment by owickstrom** [comment]
Thanks for the report @ford-prefect.

@safareli do you have time to take a look at this?

**Comment by safareli** [comment]
what you mean tests are not running sequentially? all tests are running sequentially by default. In your example and using sequential is even a no operation.

**Comment by ford-prefect** [comment]
@safareli you're right, this is almost certainly a problem in my tests. I'll reopen this if it's not. Sorry about the noise!

**Comment by safareli** [comment]
I didn't had similar issue, If you can create minimal example reproducing the issue will to look into it.

**Comment by ford-prefect** [comment]
For completeness, we resolved this issue -- the problem was that we were lifting a `Promise` into an `Aff` without an intermediate `Effect`, which was causing the asynchronous actions to start before ntended and to cause the break in sequential order.
