### ISSUE TITLE
build error (unknown value `flushCrumbs`) with use of purs v0.13.0

### ISSUE THREAD

**Issue by rgrover** [purescript-spec/purescript-spec#90]
I get the following build error with purs v0.13.0

```
Compiling Test.Spec.Reporter.Console
Error found:
in module Test.Spec.Reporter.Console
at bower_components/purescript-spec/src/Test/Spec/Reporter/Console.purs:49:28 - 49:39 (line 49, column 28 - line 49, column 39)

  Unknown value flushCrumbs
```

**Comment by safareli** [comment]
doing `rm -rf .pulp-cache output bower_components && bower i && pulp build` might help.

**Comment by hdgarrood** [comment]
This is not a stale output issue. The issue is that `where` scoping changed in 0.13.0. The relevant code is:

```purescript
    Event.Suite name -> pure (pushCrumb name s)
    Event.SuiteEnd -> pure (popCrumb s)
    Event.Pass name _ _ -> flushCrumbs do
      log $ "  " <> (colored Color.Checkmark "✓︎" <> " " <> colored Color.Pass name)
    Event.Pending name -> flushCrumbs do
      log $ "  " <> (colored Color.Pending $ "~ " <> name)
    Event.Fail name msg _ -> flushCrumbs do
      log $ "  " <> (colored Color.Fail $ "✗ " <> name <> ":")
      log ""
      log $ colored Color.Fail $ "  " <> msg
    Event.End results -> s <$ printSummary results
    _ -> pure s
      where
      flushCrumbs action = [...]
```

I can reproduce it by checking out v3.1.0 and running the command you specify with `purs 0.13.0` on my PATH. However, it is already fixed in master. Could we possibly have a new release plesea?

**Comment by safareli** [comment]
We do have Pre-release  https://github.com/purescript-spec/purescript-spec/releases/tag/v4.0.0-rc1
as it was braking change we made pre release to get feedback from people and if something was off fix it until actual release was made. but looks like there is no issue or no one is using pre-release.

What you think would be best here. I think releasing v.3.1.1 (on some v3 branch) with the `where` fix and then releasing `v4` as it's now is best option. what you think?

**Comment by hdgarrood** [comment]
Oh yeah sorry, I didn't notice the rc release until after I posted this comment, but I'm using 4.0.0-rc1 now and it seems fine :)

I think you should release v4.0.0 whenever you feel is appropriate (I'm not familiar enough with this library to be able to offer any more detailed advice). A v3.1.1 release for 0.13.0 would be very nice to have in any case.

**Comment by safareli** [comment]
https://github.com/purescript-spec/purescript-spec/pull/91

**Comment by hdgarrood** [comment]
Thank you!
