### ISSUE TITLE
Stable v4 release

### ISSUE THREAD

**Issue by nsaunders** [purescript-spec/purescript-spec#92]
I am opening this issue as a placeholder in case anyone wants to discuss remaining tasks or attach release-related commits.

But I'm mostly just wondering whether the current "v4.0.0-rc1" tag might change at all, or if it is safe to depend on the (exact) version in a dependent project. If the latter, then this will help me close [purescript-trout#12](https://github.com/owickstrom/purescript-trout/pull/12).

Thanks for your great work on this library!

**Comment by owickstrom** [comment]
@safareli What do you think, are we good to just retag the `rc` as `v4.0.0`? I'm not sure about its usage since released, if it's been tested in any real projects.

**Comment by safareli** [comment]
I guess we can release it we are using it and have no issue so far.

**Comment by nicholassaunders** [comment]
I did notice a reference to `run` with its old type in docs/index.html. I will be happy to review and update that document as well, but my day is ending now; so I will provide an update soon.

**Comment by nicholassaunders** [comment]
Travis confit also needs update.

**Comment by safareli** [comment]
tagged v4

https://github.com/purescript-spec/purescript-spec/releases/tag/v4.0.0

thanks for the effort

**Comment by nsaunders** [comment]
Awesome, thanks @safareli !
