### ISSUE TITLE
Docs don't point to the updated v4.0.0 ones

### ISSUE THREAD

**Issue by JordanMartinez** [purescript-spec/purescript-spec#99]
The ReadMe links to this page: https://purescript-spec.github.io/purescript-spec/

However, the actual docs for things like Hooks (https://github.com/purescript-spec/purescript-spec/blob/master/docs/writing-specs.md) aren't included.

**Comment by owickstrom** [comment]
@JordanMartinez Thanks for pointing this out. I've rebuilt and published the docs. Please verify that you're seeing the latest documentation at https://purescript-spec.github.io/purescript-spec/.

**Comment by JordanMartinez** [comment]
Yup! Thanks for fixing that so quickly!
